-- Product photos: a place to store a real photo URL per catalog item,
-- plus a Supabase Storage bucket admins can upload into. Nothing here
-- shows a fake/stock photo -- image_url stays null (falling back to the
-- existing icon design in the UI) until a real photo is uploaded.
alter table public.inventory add column if not exists image_url text;

insert into storage.buckets (id, name, public)
values ('item-images', 'item-images', true)
on conflict (id) do nothing;

drop policy if exists "item-images: public can read" on storage.objects;
create policy "item-images: public can read"
  on storage.objects for select
  using (bucket_id = 'item-images');

drop policy if exists "item-images: admin can upload" on storage.objects;
create policy "item-images: admin can upload"
  on storage.objects for insert
  with check (bucket_id = 'item-images' and is_admin());

drop policy if exists "item-images: admin can update" on storage.objects;
create policy "item-images: admin can update"
  on storage.objects for update
  using (bucket_id = 'item-images' and is_admin());

drop policy if exists "item-images: admin can delete" on storage.objects;
create policy "item-images: admin can delete"
  on storage.objects for delete
  using (bucket_id = 'item-images' and is_admin());

-- Testimonials: starts empty on purpose -- no fabricated reviews. Admins
-- add real ones (student name or "Hostel Block A student" for anonymity)
-- as they come in; the site should only show a testimonials section once
-- at least one real row exists.
create table if not exists public.testimonials (
  id bigint generated by default as identity primary key,
  author_label text not null,
  quote text not null,
  hostel_block text,
  approved boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.testimonials enable row level security;

drop policy if exists "testimonials: readable by everyone" on public.testimonials;
create policy "testimonials: readable by everyone"
  on public.testimonials for select
  using (approved = true);

drop policy if exists "testimonials: admin can insert" on public.testimonials;
create policy "testimonials: admin can insert"
  on public.testimonials for insert
  with check (is_admin());

drop policy if exists "testimonials: admin can update" on public.testimonials;
create policy "testimonials: admin can update"
  on public.testimonials for update
  using (is_admin());

drop policy if exists "testimonials: admin can delete" on public.testimonials;
create policy "testimonials: admin can delete"
  on public.testimonials for delete
  using (is_admin());
