-- Adds the "partner" role (rental partner who preps inventory ahead of
-- delivery) and a comments table for the Circles feed.
--
-- Partner dashboard design note: partners are external vendors, not Rently
-- staff, so they should NOT see individual students' names/rooms/bookings
-- the way admin/transporter do. Instead they get an aggregate demand count
-- per item (via a SECURITY DEFINER function, same pattern as is_admin()/
-- is_transporter()) so they know what to prepare without any student PII
-- ever being exposed to them.

-- 1. Allow 'partner' as a role value.
alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles add constraint profiles_role_check
  check (role = any (array['student'::text, 'admin'::text, 'transporter'::text, 'partner'::text]));

-- 2. is_partner(), mirroring is_admin()/is_transporter().
create or replace function public.is_partner()
returns boolean
language sql
stable security definer
set search_path = 'public'
as $$
  select exists (select 1 from public.profiles where id = auth.uid() and role = 'partner');
$$;

grant execute on function public.is_partner() to authenticated, anon;

-- 3. Aggregate demand per item, computed without exposing individual
-- bookings -- only accessible to partner/admin (the WHERE clause acts as
-- the authorization gate: anyone else gets zero rows back).
create or replace function public.get_item_demand()
returns table(item_id text, demand bigint)
language sql
stable security definer
set search_path = 'public'
as $$
  select unnest(items) as item_id, count(*) as demand
  from public.bookings
  where status in ('Pending', 'Confirmed')
    and (is_partner() or is_admin())
  group by item_id;
$$;

grant execute on function public.get_item_demand() to authenticated;

-- 4. Comments on the Circles feed. post_id is a plain text key matching
-- the feed item ids in the site's code (wifi-maintenance, cycle-rental,
-- technovee-event) -- there's no posts table to foreign-key against since
-- those feed items are still curated in code, not database rows.
create table if not exists public.circle_comments (
  id bigint generated by default as identity primary key,
  post_id text not null,
  author_id uuid not null references auth.users(id),
  author_name text not null default '',
  body text not null,
  created_at timestamptz not null default now()
);

alter table public.circle_comments enable row level security;

drop policy if exists "circle_comments: read when authenticated" on public.circle_comments;
create policy "circle_comments: read when authenticated"
  on public.circle_comments for select
  using (auth.uid() is not null);

drop policy if exists "circle_comments: insert own" on public.circle_comments;
create policy "circle_comments: insert own"
  on public.circle_comments for insert
  with check (auth.uid() = author_id);

drop policy if exists "circle_comments: author or admin can delete" on public.circle_comments;
create policy "circle_comments: author or admin can delete"
  on public.circle_comments for delete
  using (auth.uid() = author_id or is_admin());

-- To actually create a partner account: sign someone up normally through
-- the site, then in the SQL editor run (replace the email):
--   update public.profiles set role = 'partner'
--   where id = (select id from auth.users where email = 'partner@example.com');
